# This action is centrally managed in https://github.com/asyncapi/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in above mentioned repo

# It uses Github actions to listen for comments on issues and pull requests and 
# if the comment contains /ping-for-attention or /pfa it will add a comment pinging 
# the code-owners who have not yet reviewed the pull request

name: ping-for-attention

on:
  issue_comment:
    types: [created]

jobs:
  ping-for-attention:
    if: >
      github.event.issue.pull_request &&
      github.event.issue.state != 'closed' &&
      github.actor != 'asyncapi-bot' &&
      (
        contains(github.event.comment.body, '/re') ||
        contains(github.event.comment.body, '/pfa')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Check for Ping for Attention Command
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const prDetailsUrl = context.payload.issue.pull_request.url;
            const { data: pull } = await github.request(prDetailsUrl);
            const reviewers = pull.requested_reviewers.map(reviewer => reviewer.login);

            const reviewsUrl = pull.url + '/reviews';
            const { data: reviews } = await github.request(reviewsUrl);
            console.log("reviews",reviews);
            const reviewersWhoHaveReviewed = reviews.map(review => review.user.login);
            console.log("reviewersWhoHave",reviewersWhoHaveReviewed);
            const reviewersWhoHaveNotReviewed = reviewers.filter(reviewer => !reviewersWhoHaveReviewed.includes(reviewer));
            console.log("reviewed",reviewersWhoHaveNotReviewed);
            if (reviewersWhoHaveNotReviewed.length > 0) {
              const comment = reviewersWhoHaveNotReviewed.map(reviewer => `@${reviewer}`).join(' ');
              const commentUrl = pull.url + '/comments';
                await github.request(commentUrl, {
                    method: 'POST',
                    headers: {
                    'content-type': 'application/json',
                    },
                    body: JSON.stringify({
                    body: `@${github.actor} pinged ${comment} for attention`,
                    }),
                });
            }
