# This action is centrally managed in https://github.com/asyncapi/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in above mentioned repo

# It uses Github actions to listen for comments on issues and pull requests and 
# if the comment contains /ping-for-attention or /pfa it will add a comment pinging 
# the code-owners who have not yet reviewed the pull request

name: ping-for-attention

on:
  issue_comment:
    types: [created]

jobs:
  ping-for-attention:
    if: >
      github.event.issue.pull_request &&
      github.event.issue.state != 'closed' &&
      github.actor != 'asyncapi-bot' &&
      (
        contains(github.event.comment.body, '/re') ||
        contains(github.event.comment.body, '/pfa')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Check for Ping for Attention Command
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const prDetailsUrl = context.payload.issue.pull_request.url;
            const { data: pull } = await github.request(prDetailsUrl);
            console.log(pull)

            const reviewers = pull.data.requested_reviewers.map(reviewer => reviewer.login);

            const reviews = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const reviewersWhoHaveReviewed = reviews.data.map(review => review.user.login);

            const reviewersWhoHaveNotReviewed = reviewers.filter(reviewer => !reviewersWhoHaveReviewed.includes(reviewer));

            if (reviewersWhoHaveNotReviewed.length > 0) {
              const comment = reviewersWhoHaveNotReviewed.map(reviewer => `@${reviewer}`).join(' ');
              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `Ping for Attention: ${comment}`
              });
            }
